stages:
    - test
    - deploy

test-job:
    stage: test
    image: python
    before_script:
        - pip install --no-cache-dir --upgrade pip
        - pip install --no-cache-dir -r requirements.txt
    script:
        - pytest sdq

build-job:
    stage: deploy
    image: docker:dind
    before_script:
        - echo $DOCKER_GKE_AUTHKEY | docker login -u _json_key_base64 --password-stdin https://us-east1-docker.pkg.dev
    script:
        - docker build -t sdq .
        - docker tag sdq us-east1-docker.pkg.dev/sdq1-382716/sdq/sdq:$CI_COMMIT_SHA
        - docker push us-east1-docker.pkg.dev/sdq1-382716/sdq/sdq:$CI_COMMIT_SHA
