stages:
    - deploy

deploy-job:
    stage: deploy
    image: 
        name: bitnami/kubectl:latest
        entrypoint: ['']
    before_script:
        - echo $GKE_KUBECONFIG | base64 -d > gke_kubeconfig
        - export KUBECONFIG=gke_kubeconfig
    script:
        - kubectl config get-contexts
        - kubectl get pods
