stages:
    - deploy

deploy-job:
    stage: deploy
    image: 
        name: bitnami/kubectl:latest
        entrypoint: ['']
    before_script:
        - echo $KUBE_CONFIG_AWS | base64 -d > config
        - mv config ~/.kube/
    script:
        kubectl config get-contexts
