[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sdq"
version = "0.1.0"
description = "SDQ - Sadaqah - Charity"
authors = [
    {name = "Nicholas Merchant", email = "nicholaskiranmerchant@gmail.com"}
]

dependencies = [
    "Flask"
]
